version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r sttm/requirements.txt -t sttm

artifacts:
  base-directory: sttm
  files:
    - '**/*'
  type: zip

cache:
  paths:
    - /root/.cache/pip
